# Copyright (c) OpenMMLab. All rights reserved.
from .ae_head import AssociativeEmbeddingHead
from .cid_head import CIDHead
from .cpm_head import CPMHead
from .heatmap_head import HeatmapHead
from .internet_head import InternetHead
from .mspn_head import MSPNHead
from .vipnas_head import ViPNASHead
from .custom_heatmap_head import CustomHeatmapHead
from .custom_mo2cap2_heatmap_head import CustomMo2Cap2HeatmapHead
from .custom_mo2cap2_baselinel1_head import CustomMo2Cap2Baselinel1
from .custom_mo2cap2_baselinel1_head_multi_backbone import CustomMo2Cap2Baselinel1_multi_backbone
from .custom_egopose_baselinel1_head import CustomxRegoposeBaselinel1
from .custom_egopose_baselinel1_head_multi_backbone import CustomxRegoposeBaselinel1_multi_backbone
from .custom_egopose_baselinel1_head_multi_backbone_v2 import CustomxRegoposeBaselinel1_multi_backbone_v2
from .custom_egopose_baselinel1_head_seg_depth import CustomxRegoposeBaselinel1_multi_backbone_segdepth
from .custom_egopose_confidence_weighted_head import ConfidenceWeightedHMDHead
from .custom_egopose_lifting_head import CustomEgoposeLiftingHead
from .custom_egopose_lifting_backbone_fusion_head import CustomEgoposeLiftingBackboneFusionHead
from .custom_egopose_spatial_lifting_head import CustomEgoposeSpatialLiftingHead
from .custom_egopose_attention_lifting_head import CustomEgoposeAttentionLiftingHead
from .custom_egopose_skeleton_gat_head import CustomEgoposeSkeletonGATHead
from .custom_egopose_global_attention_lifting_head import CustomEgoposeGlobalAttentionLiftingHead
from .custom_egopose_heatmap_attention_lifting_head import CustomEgoposeHeatmapAttentionLiftingHead
from .custom_egopose_vit_lifting_head import CustomEgoposeViTLiftingHead
from .custom_egopose_vit_lifting_head_v5 import CustomEgoposeViTLiftingHeadV5
from .custom_egopose_hybrid_lifting_head import CustomEgoposeHybridLiftingHead
from .custom_egopose_decoupled_head import CustomEgoposeDecoupledHead
from .custom_egopose_hierarchical_head import CustomEgoposeHierarchicalHead
from .custom_egopose_vit_lifting_head_v6 import CustomEgoposeViTLiftingHeadV6
from .custom_egopose_attention_z_encoder_head import CustomEgoposeAttentionZEncoderHead
from .custom_egopose_cascaded_refinement_head import CustomEgoposeCascadedRefinementHead
from .custom_egopose_cascaded_refinement_head_v2 import CustomEgoposeCascadedRefinementHeadV2
from .custom_egopose_baselinel1_head_enhanced_hmd import CustomxRegoposeBaselinel1_enhanced_hmd
from .custom_egopose_cascaded_refinement_head_enhanced import CustomEgoposeCascadedRefinementHead_enhanced
from .custom_egopose_cascaded_refinement_head_depth import CustomEgoposeCascadedRefinementHead_depth
from .custom_egopose_hmd_attention_fusion_head import CustomEgoposeHMDAttentionFusionHead
from .custom_mo2cap2_cascaded_refinement_head_enhanced import CustomMo2Cap2CascadedRefinementHead_enhanced
from .custom_mo2cap2_baseline_head import CustomMo2Cap2BaselineHead

__all__ = [
    'HeatmapHead', 'CPMHead', 'MSPNHead', 'ViPNASHead',
    'AssociativeEmbeddingHead', 'CIDHead', 'InternetHead',
	'CustomHeatmapHead', 'CustomMo2Cap2HeatmapHead', 'CustomMo2Cap2Baselinel1', 'CustomMo2Cap2Baselinel1_multi_backbone',
	'CustomxRegoposeBaselinel1_multi_backbone', 'CustomxRegoposeBaselinel1_multi_backbone_v2',
	'CustomxRegoposeBaselinel1',
	'CustomxRegoposeBaselinel1_multi_backbone_segdepth', 'ConfidenceWeightedHMDHead',
	'CustomEgoposeLiftingHead', 'CustomEgoposeLiftingBackboneFusionHead',
	'CustomEgoposeSpatialLiftingHead', 'CustomEgoposeAttentionLiftingHead',
	'CustomEgoposeSkeletonGATHead',
	'CustomEgoposeGlobalAttentionLiftingHead',
	'CustomEgoposeHeatmapAttentionLiftingHead',
	'CustomEgoposeViTLiftingHead',
	'CustomEgoposeViTLiftingHeadV5',
	'CustomEgoposeHybridLiftingHead',
	'CustomEgoposeDecoupledHead',
	'CustomEgoposeHierarchicalHead',
	'CustomEgoposeViTLiftingHeadV6',
	'CustomEgoposeAttentionZEncoderHead',
	'CustomEgoposeCascadedRefinementHead',
	'CustomEgoposeCascadedRefinementHeadV2',
	'CustomxRegoposeBaselinel1_enhanced_hmd',
	'CustomEgoposeCascadedRefinementHead_enhanced',
	'CustomEgoposeCascadedRefinementHead_depth',
	'CustomEgoposeHMDAttentionFusionHead',
	'CustomMo2Cap2CascadedRefinementHead_enhanced',
	'CustomMo2Cap2BaselineHead'
]
