# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# config file

dataset:
  train: /dataset/data/Dataset/TrainSet
  val: /dataset/data/Dataset/ValSet
  test: /dataset/data/Dataset/TestSet

transforms:
  norm: Neck

data_loader:
  batch_size: 32
  shuffle: True

eval:
  output_file: /dataset/data/baseline602_1(coord).json